# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  up:
    cmds:
      - docker compose -f ./misc/docker/compose.yml up --build
  down:
    cmds:
      - docker compose -f ./misc/docker/compose.yml down
  exec:
    cmds:
      - docker compose -f ./misc/docker/compose.yml exec db bash
